# Generated by Django 6.0 on 2025-12-26 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AISummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("summary_json", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "AI Summaries",
                "ordering": ["-week_start"],
            },
        ),
        migrations.CreateModel(
            name="Blocker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("blocking_reason", models.TextField()),
                ("waiting_on", models.CharField(max_length=100)),
                ("hours_lost", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("resolved", "Resolved")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100, unique=True)),
                ("confidence_level", models.IntegerField(default=1)),
                ("last_used", models.DateTimeField(default=django.utils.timezone.now)),
                ("times_mentioned", models.IntegerField(default=1)),
            ],
            options={
                "ordering": ["-confidence_level", "-times_mentioned"],
            },
        ),
        migrations.CreateModel(
            name="WorkEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("hours_spent", models.FloatField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("coding", "Coding"),
                            ("meeting", "Meeting"),
                            ("learning", "Learning"),
                            ("review", "Code Review"),
                            ("bug_fix", "Bug Fix"),
                            ("documentation", "Documentation"),
                        ],
                        default="coding",
                        max_length=20,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("learning_notes", models.TextField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("github", "GitHub"),
                            ("calendar", "Calendar"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "Work Entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
