# Generated by Django 6.0 on 2025-12-26 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                ("github_username", models.CharField(max_length=100)),
                (
                    "connected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
