# Generated by Django 4.2.27 on 2025-12-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_githubintegration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blocker",
            name="waiting_on",
            field=models.CharField(max_length=200),
        ),
    ]
