# Generated by Django 4.2.27 on 2025-12-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_projects_and_calendar"),
        ("api", "0003_alter_blocker_waiting_on"),
    ]

    operations = []
